[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "demo-project"
  NEXT_PUBLIC_SANITY_DATASET = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200